multipass: true
plugins:
  - removeDimensions: true
  - prefixIds: true

  - removeViewBox: false
  - cleanupIDs: false
  - cleanupAttrs: false
  - inlineStyles: false
  - removeDoctype: false
  - removeXMLProcInst: false
  - removeComments: false
  - removeMetadata: false
  - removeTitle: false
  - removeDesc: false
  - removeUselessDefs: false
  - removeEditorsNSData: false
  - removeEmptyAttrs: false
  - removeHiddenElems: false
  - removeEmptyText: false
  - removeEmptyContainers: false
  - cleanupEnableBackground: false
  - minifyStyles: false
  - convertStyleToAttrs: false
  - convertColors: false
  - convertPathData: false
  - convertTransform: false
  - removeUnknownsAndDefaults: false
  - removeNonInheritableGroupAttrs: false
  - removeUselessStrokeAndFill: false
  - removeUnusedNS: false
  - cleanupNumericValues: false
  - moveElemsAttrsToGroup: false
  - moveGroupAttrsToElems: false
  - collapseGroups: false
  - mergePaths: false
  - convertShapeToPath: false
  - convertEllipseToCircle: false
  - sortDefsChildren: false
